on:
  push:
    branches:
    - master
    
jobs:
  build:
    name: build aplikasi
    runs-on: ubuntu-latest
    steps:
    - name: menampilkan text
      run: echo "Ini step untuk build aplikasi"
      
  test:
    name: test aplikasi
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: menampilkan text
      run: echo "Ini step untuk testing aplikasi"
      
  deploy:
    name: deploy aplikasi ke server
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: menampilkan text
      run: echo "Ini step untuk deploy aplikasi ke server linux"
    - name: deploy aplikasi ke server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST  }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          rm -rf belajar-github-batch-6
          git clone git@github.com:diansyahirfan/belajar-github-batch-6.git
          sudo mv belajar-github-batch-6/* /var/www/html/